Message.create(greeting: "Rails is the best")
Message.create(greeting: "I like JavaScript")
Message.create(greeting: "React vs Angular")
Message.create(greeting: "Python is my passion")
Message.create(greeting: "Ruby is the number 1")